
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://dianaruth.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /cs373-blog

# Google tracking id to track your visitors

google-tracking-id: "UA-72750199-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Diana Ruth"
title: "CS373 Spring 2016: Diana Ruth"
description: "Diana Ruth's blog for CS373: Software Engineering during the Spring semester of 2016"
favicon: "/img/black-lab-glass.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/background.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Good things are going to happen."
  - text: "Where’s your will to be weird?"
  - text: "Stay away from people who make you feel you're hard to love."
  - text: "Follow your heart but take your brain with you."
  - text: "Bears. Beets. Battlestar Galactica."

me-img: "/img/headshot.png"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

syntax-highlight: True

############
# Timeline #
############

#events:
#  - image: "/img/timeline/spidertocat.png"
#    date: "September 2013 - Today"
#    description: "Saving the neighborhood!"
#  - image: "/img/timeline/baracktocat.jpg"
#    date: "September 2007 - August 2013"
#    description: "Started coding"

# First image of the Timeline

#timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "hello@dianaruth.me"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/diana.ruth.16"
  - title: "linkedin"
    url: "https://www.linkedin.com/pub/diana-ruth/81/a39/bab"
  - title: "youtube"
    url: "https://www.youtube.com/channel/UCDv_zt5mQC0mGGY-8wS9YxA"
  - title: "github"
    url: "https://github.com/dianaruth"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  #Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
